services:
  kindle-ha-dashboard:
    container_name: kindle-ha-dashboard
    restart: unless-stopped
    build: .
    network_mode: host
    ports:
    - "8100:8100"
    environment:
      - HA_TOKEN=
      - HA_URL=
      - EXCLUDE_ENTITY=
      - INTERVAL=
      - SHOW_HEADER=
